server:
  port: 8088

logging:
  path: logs
  file: mylog.log

spring:
    application:
      name: userManager
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybase
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*